"use client";
import Link from "next/link";
import styles from "./Hero.module.css";

export function Hero() {
  return (
    <section className={styles.hero}>
      <div className="frame">
        <div className={styles.grid}>
          {/* Left — copy. Sits in cols 1–8 but heading is slightly outdented. */}
          <div className={styles.copy}>
            <h1 className={styles.title}>
              Fine-tune open-source models on your data.
            </h1>

            <p className={styles.sub}>
              We benchmark base models for your domain, generate the training dataset,
              run the fine-tune on dedicated GPUs, and hand you a private model your
              team self-hosts. Half on start, half when it works.
            </p>

            <div className={styles.cta}>
              <a href="mailto:founders@otune.ai?subject=Quote%20request" className={styles.action}>
                <span>Get a quote</span>
                <span aria-hidden className={styles.arrow}>→</span>
              </a>
              <span className={styles.ctaNote}>
                or email <a href="mailto:founders@otune.ai">founders@otune.ai</a> — we reply same day.
              </span>
            </div>
          </div>

          {/* Right — a real-feeling product artifact. */}
          <aside className={styles.artifact} aria-label="Sample model recommendation">
            <div className={styles.cardHead}>
              <span className={styles.cardLabel}>benchmark-report.json</span>
              <span className={styles.cardDot} />
            </div>
            <pre className={styles.code}>
{`{
  "domain": "medical device support",
  "shortlist": [
    {
      "model": "Qwen2.5-14B-Instruct",
      "score": 0.847,
      "license": "Apache-2.0",
      "fit": "recommended"
    },
    {
      "model": "Llama-3.1-8B",
      "score": 0.812,
      "license": "Llama-3 community",
      "fit": "fallback"
    }
  ],
  "dataset_rows": 6800,
  "gpu_hours_est": 9.4,
  "quote_usd": 11400
}`}
            </pre>
            <div className={styles.cardFoot}>
              <span>generated by O&rsquo;Tune research agent</span>
              <span className={styles.cardFootR}>00:01:47</span>
            </div>
          </aside>
        </div>

        {/* Off-grid stat strip, slightly offset from the title — intentional. */}
        <div className={styles.stats}>
          <Stat k="Starting at" v="$4,900" />
          <Stat k="Median delivery" v="~6 hours" />
          <Stat k="Weights" v="100% yours" />
          <Stat k="Data egress" v="Zero" />
        </div>

        <p className={styles.workingWith}>
          We&rsquo;re currently shipping models for teams in legal research, medical device
          support, and developer tooling.
        </p>
      </div>
    </section>
  );
}

function Stat({ k, v }: { k: string; v: string }) {
  return (
    <div className={styles.stat}>
      <span className={styles.statK}>{k}</span>
      <span className={styles.statV}>{v}</span>
    </div>
  );
}
